POSTGRES_USER: "postgres"
POSTGRES_PASSWORD: "postgres"
DOCKER_REGISTRY_HOST: "acm:5000"
DOCKER_IMAGE_VERSION: "v1"
DOCKER_IMAGE_VOTE: "eva/vote"
DOCKER_IMAGE_RESULT: "eva/result"
DOCKER_IMAGE_WORKER: "eva/worker"
